### ISSUE TITLE
Instructions are out of date.

### ISSUE THREAD

**Issue by Qard** [v8/vscode-torque#4]
The instructions for building the language server don't work. It seems like they're out of date?

**Comment by jakobkummerow** [comment]
Define "don't work"? Works fine here:

```
~/dev/v8 $ autoninja -C out/x64.release/ torque-language-server
ninja: Entering directory `out/x64.release/'
[1/1] Regenerating ninja files
[51/51] LINK ./torque-language-server
```

**Comment by celmaun** [comment]
@jakobkummerow 
```
[salmatron@pc v8]$ autoninja -C out/x64.release/ torque-language-server
ninja: Entering directory `out/x64.release/'
ninja: error: loading 'build.ninja': No such file or directory
```

There are zero `.ninja` files anywhere in the v8 repos.

**Comment by jakobkummerow** [comment]
Sure, `.ninja` files aren't checked in, they're generated. If you've compiled V8 before, you have them. If you haven't, type `tools/dev/gm.py x64.release` or see https://v8.dev/docs/build for more details.
